apiVersion: al-assad.github.io/v1beta1
kind: DorisCluster
metadata:
  name: basic
spec:
  version: 2.0.3
  fe:
    baseImage: ghcr.io/linsoss/doris-fe
    replicas: 1
    requests:
      storage: 10Gi
  be:
    baseImage: ghcr.io/linsoss/doris-be
    replicas: 1
    requests:
      storage: 20Gi