name: CI

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [dev]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    
    - name: Format code
      uses: iamnotaturtle/auto-gofmt@v2.1.0
      with:
        only_changed: True
    
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=10m

  test:
    name: Doris Operator Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    
    - name: Run tests
      run: make test

  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Spelling Check
      uses:  crate-ci/typos@master